### ISSUE TITLE
Why use a separate locale package?

### ISSUE THREAD

**Issue by dBianchii** [noxify/t3-turbo-lucia#4]
Hi @noxify . Thanks for this project. I used it as a reference while adding next-international to my current t3 turbo project.

I have one question: why separate locales into another package? Is it so that it can be used in other nextjs projects at the same time? Or only for organizational reasons?

Thanks for this! I had not heard of i18n ally before. Looks awesome!

**Comment by noxify** [comment]
Hi @dBianchii,

soo sorry for the late reply.

> Is it so that it can be used in other nextjs projects at the same time?

* Yeah, could be a possible use case for this - Having some shared translation ( e.g. `Save`, `Update` ), but would work only if you plan to use generic translation ( e.g. `Create` instead of `Create Task` )


> Or only for organizational reasons?

Tbh, I can't remember why I did it as separate package - possible that it's just over-engineered :D 
If I'm not wrong, I had to use a "custom source" configuration for  i18n ally ( and read the JSON files), otherwise I got only a "blank screen".

I think you can implement the localization directly in the app, if you don't need the i18n ally extension - But with the current implementation I would keep it in a separate package, otherwise you have to add the `lang:gen` command in each app ( or use something else which generates the `ts` files.

----

Hope that makes sense, haven't checked the code and/or if it's now possible to read the ts files directly / using the `next-international` configuration from i18n ally.

**Comment by noxify** [comment]
As mentioned in #6 it seems that we could read the `ts` files directly, but they are read-only.
I assumed it's based on the "nested structure", but got the same result with a "flat structure".

I think using the json files is currently the "way to go" if you want to use the Editor UI from i18n-ally.

I have seen that there are some issues/PRs in their repo.

Will close this issue for now - if there is something else, please let know :)
